name: cse702027_project_mobile
description: "Personal Expense Manager – Flutter (Material 3, Provider)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'   # Sửa từ ^3.9.0 → khoảng tương thích ổn định

dependencies:
  flutter:
    sdk: flutter

  # i18n (đa ngôn ngữ)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2   # khớp SDK

  # State management
  provider: ^6.1.2

  # Local storage (login, pref…)
  shared_preferences: ^2.3.2

  # Charts
  fl_chart: ^0.68.0

  # Icons (iOS style)
  cupertino_icons: ^1.0.8

  # (Tuỳ chọn) đổi tên ứng dụng/bundle id qua CLI
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # Khai báo assets cho hình ảnh giao diện
  assets:
    - assets/img/

  # (Tuỳ chọn) fonts…
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
